---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sql.mssql.microsoft.com
  resources:
  - sqlserveravailabilitygroups
  - sqlserverinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sql.mssql.microsoft.com
  resources:
  - sqlserveravailabilitygroups/finalizers
  - sqlserverinstances/finalizers
  verbs:
  - update
- apiGroups:
  - sql.mssql.microsoft.com
  resources:
  - sqlserveravailabilitygroups/status
  - sqlserverinstances/status
  verbs:
  - get
  - patch
  - update
