name: E2E Tests

on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 55
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-$(go env GOARCH)
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the manager image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: sql-on-k8s-operator:latest
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Kind cluster
        run: make setup-test-e2e

      - name: Load manager image into Kind
        run: kind load docker-image sql-on-k8s-operator:latest --name sql-on-k8s-operator-test-e2e

      - name: Running Test e2e
        env:
          BUILD_IMAGE_SKIP: "true"
          KIND_CLUSTER_SKIP: "true"
        run: |
          go mod tidy
          make test-e2e
